
export const INCREMENT_ENTHUSIASM: string = 'INCREMENT_ENTHUSIASM';
export const DECREMENT_ENTHUSIASM: string = 'DECREMENT_ENTHUSIASM';


export const CHANGE_APP_NAME: string = 'CHANGE_APP_NAME';


export const FETCH_TOP_RATED_MOVIES: string = 'FETCH_TOP_RATED_MOVIES';
export const FETCH_NOW_PLAYING_MOVIES: string = 'FETCH_NOW_PLAYING_MOVIES';
export const FETCH_POPULAR_MOVIES: string = 'FETCH_POPULAR_MOVIES';
export const FETCH_UPCOMING_MOVIES: string = 'FETCH_UPCOMING_MOVIES';
export const FETCH_MOVIE_DETAILS: string = 'FETCH_MOVIE_DETAILS';